export const MAJOR_POLLING_HUBS = [
  {
    id: "delhi-1",
    name: "Nirvachan Sadan (Election Commission HQ)",
    address: "Ashoka Rd, Pandit Pant Marg Area, New Delhi, Delhi 110001",
    city: "New Delhi",
    state: "Delhi",
    type: "National HQ",
  },
  {
    id: "delhi-2",
    name: "Modern School",
    address: "Barakhamba Rd, Todermal Road Area, Mandi House, New Delhi, Delhi 110001",
    city: "New Delhi",
    state: "Delhi",
    type: "Major Booth",
  },
  {
    id: "mumbai-1",
    name: "St. Xavier's College",
    address: "5, Mahapalika Marg, Dhobi Talao, Chhatrapati Shivaji Terminus Area, Fort, Mumbai, Maharashtra 400001",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Major Booth",
  },
  {
    id: "mumbai-2",
    name: "Elphinstone College",
    address: "156, Mahatma Gandhi Road, Mantralaya, Fort, Mumbai, Maharashtra 400032",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Major Booth",
  },
  {
    id: "bangalore-1",
    name: "Indian Institute of Science (IISc)",
    address: "CV Raman Rd, Bengaluru, Karnataka 560012",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Major Hub",
  },
  {
    id: "bangalore-2",
    name: "Mount Carmel College",
    address: "58, Palace Rd, Abshot Layout, Vasanth Nagar, Bengaluru, Karnataka 560052",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Major Booth",
  },
  {
    id: "kolkata-1",
    name: "Presidency University",
    address: "86, 1, College St, Calcutta University, College Square, Kolkata, West Bengal 700073",
    city: "Kolkata",
    state: "West Bengal",
    type: "Major Booth",
  },
  {
    id: "chennai-1",
    name: "Loyola College",
    address: "Sterling Rd, Near, Nungambakkam, Chennai, Tamil Nadu 600034",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Major Booth",
  },
  {
    id: "hyderabad-1",
    name: "Osmania University Arts College",
    address: "Osmania University, Amberpet, Hyderabad, Telangana 500007",
    city: "Hyderabad",
    state: "Telangana",
    type: "Major Hub",
  },
];
